=== jrosental/openshift-json-schemas/v4.21-local/jsonschemaprops.json
{
  "description": "JSONSchemaProps is a JSON-Schema following Specification Draft 4 (http://json-schema.org/).",
  "type": "object",
  "properties": {
    "$ref": {
      "type": "string"
    },
    "$schema": {
      "type": "string"
    },
    "additionalItems": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaPropsOrBool"
    },
    "additionalProperties": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaPropsOrBool"
    },
    "allOf": {
      "type": "array",
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps"
      },
      "x-kubernetes-list-type": "atomic"
    },
    "anyOf": {
      "type": "array",
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps"
      },
      "x-kubernetes-list-type": "atomic"
    },
    "default": {
      "description": "default is a default value for undefined object fields. Defaulting is a beta feature under the CustomResourceDefaulting feature gate. Defaulting requires spec.preserveUnknownFields to be false.",
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSON"
    },
    "definitions": {
      "type": "object",
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps"
      }
    },
    "dependencies": {
      "type": "object",
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaPropsOrStringArray"
      }
    },
    "description": {
      "type": "string"
    },
    "enum": {
      "type": "array",
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSON"
      },
      "x-kubernetes-list-type": "atomic"
    },
    "example": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSON"
    },
    "exclusiveMaximum": {
      "type": "boolean"
    },
    "exclusiveMinimum": {
      "type": "boolean"
    },
    "externalDocs": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.ExternalDocumentation"
    },
    "format": {
      "description": "format is an OpenAPI v3 format string. Unknown formats are ignored. The following formats are validated:\n\n- bsonobjectid: a bson object ID, i.e. a 24 characters hex string - uri: an URI as parsed by Golang net/url.ParseRequestURI - email: an email address as parsed by Golang net/mail.ParseAddress - hostname: a valid representation for an Internet host name, as defined by RFC 1034, section 3.1 [RFC1034]. - ipv4: an IPv4 IP as parsed by Golang net.ParseIP - ipv6: an IPv6 IP as parsed by Golang net.ParseIP - cidr: a CIDR as parsed by Golang net.ParseCIDR - mac: a MAC address as parsed by Golang net.ParseMAC - uuid: an UUID that allows uppercase defined by the regex (?i)^[0-9a-f]{8}-?[0-9a-f]{4}-?[0-9a-f]{4}-?[0-9a-f]{4}-?[0-9a-f]{12}$ - uuid3: an UUID3 that allows uppercase defined by the regex (?i)^[0-9a-f]{8}-?[0-9a-f]{4}-?3[0-9a-f]{3}-?[0-9a-f]{4}-?[0-9a-f]{12}$ - uuid4: an UUID4 that allows uppercase defined by the regex (?i)^[0-9a-f]{8}-?[0-9a-f]{4}-?4[0-9a-f]{3}-?[89ab][0-9a-f]{3}-?[0-9a-f]{12}$ - uuid5: an UUID5 that allows uppercase defined by the regex (?i)^[0-9a-f]{8}-?[0-9a-f]{4}-?5[0-9a-f]{3}-?[89ab][0-9a-f]{3}-?[0-9a-f]{12}$ - isbn: an ISBN10 or ISBN13 number string like \"0321751043\" or \"978-0321751041\" - isbn10: an ISBN10 number string like \"0321751043\" - isbn13: an ISBN13 number string like \"978-0321751041\" - creditcard: a credit card number defined by the regex ^(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\\\\d{3})\\\\d{11})$ with any non digit characters mixed in - ssn: a U.S. social security number following the regex ^\\\\d{3}[- ]?\\\\d{2}[- ]?\\\\d{4}$ - hexcolor: an hexadecimal color code like \"#FFFFFF: following the regex ^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$ - rgbcolor: an RGB color code like rgb like \"rgb(255,255,2559\" - byte: base64 encoded binary data - password: any kind of string - date: a date string like \"2006-01-02\" as defined by full-date in RFC3339 - duration: a duration string like \"22 ns\" as parsed by Golang time.ParseDuration or compatible with Scala duration format - datetime: a date time string like \"2014-12-15T19:30:20.000Z\" as defined by date-time in RFC3339.",
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "items": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaPropsOrArray"
    },
    "maxItems": {
      "type": "integer",
      "format": "int64"
    },
    "maxLength": {
      "type": "integer",
      "format": "int64"
    },
    "maxProperties": {
      "type": "integer",
      "format": "int64"
    },
    "maximum": {
      "type": "number",
      "format": "double"
    },
    "minItems": {
      "type": "integer",
      "format": "int64"
    },
    "minLength": {
      "type": "integer",
      "format": "int64"
    },
    "minProperties": {
      "type": "integer",
      "format": "int64"
    },
    "minimum": {
      "type": "number",
      "format": "double"
    },
    "multipleOf": {
      "type": "number",
      "format": "double"
    },
    "not": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps"
    },
    "nullable": {
      "type": "boolean"
    },
    "oneOf": {
      "type": "array",
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps"
      },
      "x-kubernetes-list-type": "atomic"
    },
    "pattern": {
      "type": "string"
    },
    "patternProperties": {
      "type": "object",
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps"
      }
    },
    "properties": {
      "type": "object",
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps"
      }
    },
    "required": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "x-kubernetes-list-type": "atomic"
    },
    "title": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "uniqueItems": {
      "type": "boolean"
    },
    "x-kubernetes-embedded-resource": {
      "description": "x-kubernetes-embedded-resource defines that the value is an embedded Kubernetes runtime.Object, with TypeMeta and ObjectMeta. The type must be object. It is allowed to further restrict the embedded object. kind, apiVersion and metadata are validated automatically. x-kubernetes-preserve-unknown-fields is allowed to be true, but does not have to be if the object is fully specified (up to kind, apiVersion, metadata).",
      "type": "boolean"
    },
    "x-kubernetes-int-or-string": {
      "description": "x-kubernetes-int-or-string specifies that this value is either an integer or a string. If this is true, an empty type is allowed and type as child of anyOf is permitted if following one of the following patterns:\n\n1) anyOf:\n   - type: integer\n   - type: string\n2) allOf:\n   - anyOf:\n     - type: integer\n     - type: string\n   - ... zero or more",
      "type": "boolean"
    },
    "x-kubernetes-list-map-keys": {
      "description": "x-kubernetes-list-map-keys annotates an array with the x-kubernetes-list-type `map` by specifying the keys used as the index of the map.\n\nThis tag MUST only be used on lists that have the \"x-kubernetes-list-type\" extension set to \"map\". Also, the values specified for this attribute must be a scalar typed field of the child structure (no nesting is supported).\n\nThe properties specified must either be required or have a default value, to ensure those properties are present for all list items.",
      "type": "array",
      "items": {
        "type": "string"
      },
      "x-kubernetes-list-type": "atomic"
    },
    "x-kubernetes-list-type": {
      "description": "x-kubernetes-list-type annotates an array to further describe its topology. This extension must only be used on lists and may have 3 possible values:\n\n1) `atomic`: the list is treated as a single entity, like a scalar.\n     Atomic lists will be entirely replaced when updated. This extension\n     may be used on any type of list (struct, scalar, ...).\n2) `set`:\n     Sets are lists that must not have multiple items with the same value. Each\n     value must be a scalar, an object with x-kubernetes-map-type `atomic` or an\n     array with x-kubernetes-list-type `atomic`.\n3) `map`:\n     These lists are like maps in that their elements have a non-index key\n     used to identify them. Order is preserved upon merge. The map tag\n     must only be used on a list with elements of type object.\nDefaults to atomic for arrays.",
      "type": "string"
    },
    "x-kubernetes-map-type": {
      "description": "x-kubernetes-map-type annotates an object to further describe its topology. This extension must only be used when type is object and may have 2 possible values:\n\n1) `granular`:\n     These maps are actual maps (key-value pairs) and each fields are independent\n     from each other (they can each be manipulated by separate actors). This is\n     the default behaviour for all maps.\n2) `atomic`: the list is treated as a single entity, like a scalar.\n     Atomic maps will be entirely replaced when updated.",
      "type": "string"
    },
    "x-kubernetes-preserve-unknown-fields": {
      "description": "x-kubernetes-preserve-unknown-fields stops the API server decoding step from pruning fields which are not specified in the validation schema. This affects fields recursively, but switches back to normal pruning behaviour if nested properties or additionalProperties are specified in the schema. This can either be true or undefined. False is forbidden.",
      "type": "boolean"
    },
    "x-kubernetes-validations": {
      "description": "x-kubernetes-validations describes a list of validation rules written in the CEL expression language.",
      "type": "array",
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.ValidationRule"
      },
      "x-kubernetes-list-map-keys": [
        "rule"
      ],
      "x-kubernetes-list-type": "map",
      "x-kubernetes-patch-merge-key": "rule",
      "x-kubernetes-patch-strategy": "merge"
    },
    "apiVersion": {
      "type": "string"
    },
    "kind": {
      "type": "string"
    },
    "metadata": {
      "type": "object"
    }
  },
  "$schema": "http://json-schema.org/schema#"
}

=== jrosental/openshift-json-schemas/v4.21-standalone-strict/buildstatus.json
{
  "description": "BuildStatus contains the status of a build",
  "type": "object",
  "required": [
    "phase"
  ],
  "properties": {
    "cancelled": {
      "description": "cancelled describes if a cancel event was triggered for the build.",
      "type": "boolean"
    },
    "completionTimestamp": {
      "description": "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.",
      "type": "string",
      "format": "date-time"
    },
    "conditions": {
      "description": "Conditions represents the latest available observations of a build's current state.",
      "type": "array",
      "items": {
        "description": "BuildCondition describes the state of a build at a certain point.",
        "type": "object",
        "required": [
          "type",
          "status"
        ],
        "properties": {
          "lastTransitionTime": {
            "description": "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.",
            "type": "string",
            "format": "date-time"
          },
          "lastUpdateTime": {
            "description": "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.",
            "type": "string",
            "format": "date-time"
          },
          "message": {
            "description": "A human readable message indicating details about the transition.",
            "type": "string"
          },
          "reason": {
            "description": "The reason for the condition's last transition.",
            "type": "string"
          },
          "status": {
            "description": "Status of the condition, one of True, False, Unknown.",
            "type": "string"
          },
          "type": {
            "description": "Type of build condition.",
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "x-kubernetes-patch-merge-key": "type",
      "x-kubernetes-patch-strategy": "merge"
    },
    "config": {
      "description": "ObjectReference contains enough information to let you inspect or modify the referred object.",
      "type": "object",
      "properties": {
        "apiVersion": {
          "description": "API version of the referent.",
          "type": "string"
        },
        "fieldPath": {
          "description": "If referring to a piece of an object instead of an entire object, this string should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2]. For example, if the object reference is to a container within a pod, this would take on a value like: \"spec.containers{name}\" (where \"name\" refers to the name of the container that triggered the event) or if no container name is specified \"spec.containers[2]\" (container with index 2 in this pod). This syntax is chosen only to have some well-defined way of referencing a part of an object.",
          "type": "string"
        },
        "kind": {
          "description": "Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
          "type": "string"
        },
        "name": {
          "description": "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names",
          "type": "string"
        },
        "namespace": {
          "description": "Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/",
          "type": "string"
        },
        "resourceVersion": {
          "description": "Specific resourceVersion to which this reference is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency",
          "type": "string"
        },
        "uid": {
          "description": "UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids",
          "type": "string"
        }
      },
      "x-kubernetes-map-type": "atomic",
      "additionalProperties": false
    },
    "duration": {
      "description": "duration contains time.Duration object describing build time.",
      "type": "integer",
      "format": "int64"
    },
    "logSnippet": {
      "description": "logSnippet is the last few lines of the build log.  This value is only set for builds that failed.",
      "type": "string"
    },
    "message": {
      "description": "message is a human-readable message indicating details about why the build has this status.",
      "type": "string"
    },
    "output": {
      "description": "BuildStatusOutput contains the status of the built image.",
      "type": "object",
      "properties": {
        "to": {
          "description": "BuildStatusOutputTo describes the status of the built image with regards to image registry to which it was supposed to be pushed.",
          "type": "object",
          "properties": {
            "imageDigest": {
              "description": "imageDigest is the digest of the built container image. The digest uniquely identifies the image in the registry to which it was pushed.\n\nPlease note that this field may not always be set even if the push completes successfully - e.g. when the registry returns no digest or returns it in a format that the builder doesn't understand.",
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "outputDockerImageReference": {
      "description": "outputDockerImageReference contains a reference to the container image that will be built by this build. Its value is computed from Build.Spec.Output.To, and should include the registry address, so that it can be used to push and pull the image.",
      "type": "string"
    },
    "phase": {
      "description": "phase is the point in the build lifecycle. Possible values are \"New\", \"Pending\", \"Running\", \"Complete\", \"Failed\", \"Error\", and \"Cancelled\".",
      "type": "string"
    },
    "reason": {
      "description": "reason is a brief CamelCase string that describes any failure and is meant for machine parsing and tidy display in the CLI.",
      "type": "string"
    },
    "stages": {
      "description": "stages contains details about each stage that occurs during the build including start time, duration (in milliseconds), and the steps that occured within each stage.",
      "type": "array",
      "items": {
        "description": "StageInfo contains details about a build stage.",
        "type": "object",
        "properties": {
          "durationMilliseconds": {
            "description": "durationMilliseconds identifies how long the stage took to complete in milliseconds. Note: the duration of a stage can exceed the sum of the duration of the steps within the stage as not all actions are accounted for in explicit build steps.",
            "type": "integer",
            "format": "int64"
          },
          "name": {
            "description": "name is a unique identifier for each build stage that occurs.",
            "type": "string"
          },
          "startTime": {
            "description": "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.",
            "type": "string",
            "format": "date-time"
          },
          "steps": {
            "description": "steps contains details about each step that occurs during a build stage including start time and duration in milliseconds.",
            "type": "array",
            "items": {
              "description": "StepInfo contains details about a build step.",
              "type": "object",
              "properties": {
                "durationMilliseconds": {
                  "description": "durationMilliseconds identifies how long the step took to complete in milliseconds.",
                  "type": "integer",
                  "format": "int64"
                },
                "name": {
                  "description": "name is a unique identifier for each build step.",
                  "type": "string"
                },
                "startTime": {
                  "description": "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.",
                  "type": "string",
                  "format": "date-time"
                }
              },
              "additionalProperties": false
            }
          }
        },
        "additionalProperties": false
      }
    },
    "startTimestamp": {
      "description": "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.",
      "type": "string",
      "format": "date-time"
    },
    "apiVersion": {
      "type": "string"
    },
    "kind": {
      "type": "string"
    },
    "metadata": {
      "type": "object"
    }
  },
  "additionalProperties": false,
  "$schema": "http://json-schema.org/schema#"
}

=== jrosental/openshift-json-schemas/v4.21.5-standalone-strict/resourcequotaspec.json
{
  "description": "ResourceQuotaSpec defines the desired hard limits to enforce for Quota.",
  "type": "object",
  "properties": {
    "hard": {
      "description": "hard is the set of desired hard limits for each named resource. More info: https://kubernetes.io/docs/concepts/policy/resource-quotas/",
      "type": "object",
      "additionalProperties": {
        "description": "Quantity is a fixed-point representation of a number. It provides convenient marshaling/unmarshaling in JSON and YAML, in addition to String() and AsInt64() accessors.\n\nThe serialization format is:\n\n``` <quantity>        ::= <signedNumber><suffix>\n\n\t(Note that <suffix> may be empty, from the \"\" case in <decimalSI>.)\n\n<digit>           ::= 0 | 1 | ... | 9 <digits>          ::= <digit> | <digit><digits> <number>          ::= <digits> | <digits>.<digits> | <digits>. | .<digits> <sign>            ::= \"+\" | \"-\" <signedNumber>    ::= <number> | <sign><number> <suffix>          ::= <binarySI> | <decimalExponent> | <decimalSI> <binarySI>        ::= Ki | Mi | Gi | Ti | Pi | Ei\n\n\t(International System of units; See: http://physics.nist.gov/cuu/Units/binary.html)\n\n<decimalSI>       ::= m | \"\" | k | M | G | T | P | E\n\n\t(Note that 1024 = 1Ki but 1000 = 1k; I didn't choose the capitalization.)\n\n<decimalExponent> ::= \"e\" <signedNumber> | \"E\" <signedNumber> ```\n\nNo matter which of the three exponent forms is used, no quantity may represent a number greater than 2^63-1 in magnitude, nor may it have more than 3 decimal places. Numbers larger or more precise will be capped or rounded up. (E.g.: 0.1m will rounded up to 1m.) This may be extended in the future if we require larger or smaller quantities.\n\nWhen a Quantity is parsed from a string, it will remember the type of suffix it had, and will use the same type again when it is serialized.\n\nBefore serializing, Quantity will be put in \"canonical form\". This means that Exponent/suffix will be adjusted up or down (with a corresponding increase or decrease in Mantissa) such that:\n\n- No precision is lost - No fractional digits will be emitted - The exponent (or suffix) is as large as possible.\n\nThe sign will be omitted unless the number is negative.\n\nExamples:\n\n- 1.5 will be serialized as \"1500m\" - 1.5Gi will be serialized as \"1536Mi\"\n\nNote that the quantity will NEVER be internally represented by a floating point number. That is the whole point of this exercise.\n\nNon-canonical values will still parse as long as they are well formed, but will be re-emitted in their canonical form. (So always use canonical form, or don't diff.)\n\nThis format is intended to make it difficult to use these numbers without writing some sort of special handling code in the hopes that that will cause implementors to also use a fixed point implementation.",
        "type": "string",
        "properties": {},
        "additionalProperties": false
      }
    },
    "scopeSelector": {
      "description": "A scope selector represents the AND of the selectors represented by the scoped-resource selector requirements.",
      "type": "object",
      "properties": {
        "matchExpressions": {
          "description": "A list of scope selector requirements by scope of the resources.",
          "type": "array",
          "items": {
            "description": "A scoped-resource selector requirement is a selector that contains values, a scope name, and an operator that relates the scope name and values.",
            "type": "object",
            "required": [
              "scopeName",
              "operator"
            ],
            "properties": {
              "operator": {
                "description": "Represents a scope's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist.\n\nPossible enum values:\n - `\"DoesNotExist\"`\n - `\"Exists\"`\n - `\"In\"`\n - `\"NotIn\"`",
                "type": "string",
                "enum": [
                  "DoesNotExist",
                  "Exists",
                  "In",
                  "NotIn"
                ]
              },
              "scopeName": {
                "description": "The name of the scope that the selector applies to.\n\nPossible enum values:\n - `\"BestEffort\"` Match all pod objects that have best effort quality of service\n - `\"CrossNamespacePodAffinity\"` Match all pod objects that have cross-namespace pod (anti)affinity mentioned.\n - `\"NotBestEffort\"` Match all pod objects that do not have best effort quality of service\n - `\"NotTerminating\"` Match all pod objects where spec.activeDeadlineSeconds is nil\n - `\"PriorityClass\"` Match all pod objects that have priority class mentioned\n - `\"Terminating\"` Match all pod objects where spec.activeDeadlineSeconds >=0\n - `\"VolumeAttributesClass\"` Match all pvc objects that have volume attributes class mentioned.",
                "type": "string",
                "enum": [
                  "BestEffort",
                  "CrossNamespacePodAffinity",
                  "NotBestEffort",
                  "NotTerminating",
                  "PriorityClass",
                  "Terminating",
                  "VolumeAttributesClass"
                ]
              },
              "values": {
                "description": "An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.",
                "type": "array",
                "items": {
                  "type": "string"
                },
                "x-kubernetes-list-type": "atomic"
              }
            },
            "additionalProperties": false
          },
          "x-kubernetes-list-type": "atomic"
        }
      },
      "x-kubernetes-map-type": "atomic",
      "additionalProperties": false
    },
    "scopes": {
      "description": "A collection of filters that must match each object tracked by a quota. If not specified, the quota matches all objects.",
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "BestEffort",
          "CrossNamespacePodAffinity",
          "NotBestEffort",
          "NotTerminating",
          "PriorityClass",
          "Terminating",
          "VolumeAttributesClass"
        ]
      },
      "x-kubernetes-list-type": "atomic"
    }
  },
  "additionalProperties": false,
  "$schema": "http://json-schema.org/schema#"
}
